nameOverride: pay-api

replicaCount: 1

image:
  repository: 494313539566.dkr.ecr.eu-central-1.amazonaws.com/pay-api
  digest: sha256:4930c7df48060c953d7394adbfe7309b0b8300eb6f2f83404fcf10d1a5d15193
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: pay-api.example.internal
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  APP_VERSION: "0.1.0"
  LOG_LEVEL: info
  CURRENCY_EXCHANGE_BASE_URL: http://currency-exchange.pay-api-prod.svc.cluster.local
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: pay-api
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger.observability.svc.cluster.local:4318/v1/traces
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=prod,service.namespace=pay-api-demo
  OTEL_TRACES_SAMPLER: parentbased_always_on

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
