nameOverride: pay-api

replicaCount: 1

image:
  repository: 494313539566.dkr.ecr.eu-central-1.amazonaws.com/pay-api
  digest: sha256:640323030d230347bec07d56ea7b0ca551cd16ad47af34abd3f07a4b6b049a27
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

ingress:
  enabled: false
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: pay-api.example.internal
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  APP_VERSION: "0.1.0"
  LOG_LEVEL: info

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
