apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pay-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pay-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pay-api.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pay-api.name" . }}
    spec:
      containers:
        - name: pay-api
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          env:
            - name: APP_VERSION
              value: {{ .Values.env.APP_VERSION | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
