apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pay-api-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<GITHUB_ORG>/<GITOPS_REPOSITORY_NAME>.git
    targetRevision: main
    path: apps/pay-api-prod
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pay-api-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
